#!/bin/bash
# Bash Menu Script Example

#install library yang dibutuhkan

#service networking restart
#dhclient eth0
ip=$(ip -f inet -o addr show eth0|cut -d\  -f 7 | cut -d/ -f 1)
echo "ip anda adalah : "$ip
echo -e "nameserver 202.9.85.3\nnameserver $ip" > /etc/resolv.conf
mkdir /etc/skel/public_html
apt-get install telnetd -y
apt-get install openssh-server -y
Menu () {
    clear
    echo "
1) Update             5) Reset DNS         9) Reset MAIL
2) User               6) Install WEB      10) ResetAll
3) Install DNS        7) Reset WEB        11) Quit
4) Tambah zona dns    8) Install MAIL

  "
}
PS3='Silahkan Pilih Menunya Bos: '
options=("Update" "User" "Install DNS" "Tambah zona dns" "Reset DNS"  "Install WEB" "Reset WEB" "Install MAIL" "Reset MAIL" "ResetAll" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Update")
            # Update packages and Upgrade system
            echo -e "$Cyan \n Updating System.. $Color_Off"
            apt-get update -y
            Menu                                
            ;;
    "User")
       echo "berapa user yang ingin anda buat ?"
       read jumUser
       for (( i = 0; i < $jumUser; i++ )); do
            echo "siapa namanya $i? :"
        read namaUsers
        cp ./index.php /etc/skel/public_html
        adduser $namaUsers
        ln -s /home/$namaUsers /var/www/html/
        chown $namaUsers:$namaUsers -R /var/www/html/$namaUsers
       done
       ;;
        "Reset DNS")
            echo "Resetting bind9"
            sudo apt-get purge --auto-remove bind9 -y
            rm -R /var/cache/bind
            ;;
    "Tambah zona dns")
       echo "Menambah Dns :::"

echo "Berapa Virtual Host Yang anda Inginkan ?"
            read jumHost 
            for (( c=1; c<=$jumHost; c++ ))
            do  
               echo "Konfigurasi Host $c"
               echo "Masukkan nama host anda:"
               read nama
               echo "Masukkan nama ip host anda:"
               read iphost

cat >> /etc/bind/named.conf.local<<EOT
zone "$nama" { //zone domain
    type master; //tipe domain
    file "/var/cache/bind/db.$nama";
};
EOT

VAR="$"
TTL="TTL"
cat > /var/cache/bind/db.$nama<<EOT
; BIND reverse data file for empty rfc1918 zone
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$VAR$TTL   86400
@       IN      SOA     localhost. root.localhost. (
                              2         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                          86400 )       ; Negative Cache TTL
;
@       IN      NS      localhost.
@       IN      A       $iphost
www     IN      A       $iphost
mail    IN      A       $iphost
EOT

HOST=$(echo $iphost | cut -c12-14 )
cat >> /var/cache/bind/db.reverse<<EOT
@       IN      PTR       $nama
$HOST      IN      PTR       www.$nama
$HOST      IN      PTR       mail.$nama

EOT
done    

service bind9 restart
       ;;
        "Install DNS")
            bindconf='/etc/bind'
            bindconf2='/var/cache/bind'
            echo "Sedang Memasang Bind9 sebagai DNS Server"
            apt-get install bind9 -y
            echo "Berapa Virtual Host Yang anda Inginkan ?"
            read jumHost 
            for (( c=1; c<=$jumHost; c++ ))
            do  
               echo "Konfigurasi Host $c"
               echo "Masukkan nama host anda:"
               read nama

cat >> /etc/bind/named.conf.local<<EOT
zone "$nama" { //zone domain
    type master; //tipe domain
    file "/var/cache/bind/db.$nama";
};
EOT

VAR="$"
TTL="TTL"
cat > $bindconf2/db.$nama<<EOT
; BIND reverse data file for empty rfc1918 zone
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$VAR$TTL   86400
@       IN      SOA     localhost. root.localhost. (
                              2         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                          86400 )       ; Negative Cache TTL
;
@       IN      NS      localhost.
@       IN      A       $ip
www     IN      A       $ip
mail    IN      A       $ip
EOT

cp /etc/bind/db.empty /var/cache/bind/db.reverse
HOST=$(echo $ip | cut -c12-14 )
cat >> $bindconf2/db.reverse<<EOT
@       IN      PTR       $nama
$HOST      IN      PTR       www.$nama
$HOST      IN      PTR       mail.$nama

EOT
done    

cat >> $bindconf/named.conf.local<<EOT
zone "108.252.10.in-addr.arpa" {
        type master;
        file "/var/cache/bind/db.reverse";
};
EOT
service bind9 restart
            ;;
        "Install WEB")
            ## Install AMP
            echo -e "$Cyan \n Installing Apache2 $Color_Off"
            apt-get install apache2 apache2-doc apache2-utils php5 php-pear libapache2-mod-php5 -y

            echo -e "$Cyan \n Installing PHP & Requirements $Color_Off"
            #apt-get install libapache2-mod-php5 php5 php5-common php5-curl php5-dev php5-gd php5-idn php-pear php5-imagick php5-mcrypt php5-mysql php5-ps php5-pspell php5-recode php5-xsl -y

            # echo -e "$Cyan \n Installing MySQL $Color_Off"
            #apt-get -y install php5-mysqlnd php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl
        	apt-get -y install mariadb-server mariadb-client
            # echo -e "$Cyan \n Installing phpMyAdmin $Color_Off"
            apt-get install phpmyadmin -y

            # echo -e "$Cyan \n Verifying installs$Color_Off"
            #apt-get install apache2 libapache2-mod-php5 php5 mysql-server php-pear php5-mysql mysql-client mysql-server php5-mysql php5-gd -y

            echo -e "$Cyan \n Verifying installs$Color_Off"
            #apt-get install apache2 libapache2-mod-php5 php5 php-pear -y
            ## TWEAKS and Settings

            # Permissions
            echo -e "$Cyan \n Permissions for /var/www $Color_Off"
            chown -R www-data:www-data /var/www
            echo -e "$Green \n Permissions have been set $Color_Off"

            # Enabling Mod Rewrite, required for WordPress permalinks and .htaccess files
            echo -e "$Cyan \n Enabling Modules $Color_Off"
            a2enmod rewrite
            php5enmod mcrypt

            # membuat virtualhost
            ln -s /etc/apache2/mods-available/userdir.conf /etc/apache2/mods-enabled/
            ln -s /etc/apache2/mods-available/userdir.load /etc/apache2/mods-enabled/
            sed -i 's/php_admin_flag engine Off/#php_admin_flag engine Off/g' /etc/apache2/mods-enabled/php5.conf
            mv /var/www/html/index.html /var/www/html/xindex.html
            cp ./index.php /var/www/html

            # Restart Apache
            echo -e "$Cyan \n Restarting Apache $Color_Off"
            apt-get -f install -y
            service apache2 restart            
            ;;
        "Reset WEB")
            echo "Sedang Mereset Website... silahkan tunggu "
            apt-get purge apache2 apache2-utils apache2.2-bin  php5 -y
            rm -R /var/www/html
            rm -R /etc/apache2
            apt-get autoremove -y
            ;;
        "Install MAIL")
            echo "Mohon Bersabar ini Masih Install Mail server bos"
        	apt-get install courier-imap courier-pop courier-ssl courier-imap-ssl
            apt-get install postfix -y
            service postfix restart -y
            maildirmake /etc/skel/Maildir
            #apt-get install dovecot-imapd dovecot-pop3d -y 
            #service dovecot restart -y
            apt-get install squirrelmail -y
        	ln -s /usr/share/squirrelmail/ /var/www/squirrelmail
            cp /etc/squirrelmail/apache.conf /etc/apache2/sites-available/squirrelmail.conf
            a2ensite squirrelmail.conf
            sed -i 's/mailbox_command = procmail -a "$EXTENSION"/#mailbox_command = procmail -a "$EXTENSION"/g'  /etc/postfix/main.cf
            echo "home_mailbox = Maildir/" >> /etc/postfix/main.cf
            echo "berapa user yang ingin anda buat untuk mail server anda ?"
            read user
            for (( i = 0; i < $user; i++ )); do
                #statements
                echo "siapakah namanya ?"
                read namauser 
                adduser $namauser
                chown -R $namauser:$namauser /var/www/html/$namauser
            done
            # install roundcube
            cd /var/www/html && wget https://github.com/roundcube/roundcubemail/releases/download/1.2.9/roundcubemail-1.2.9-complete.tar.gz && tar xzvf roundcubemail-1.2.9-complete.tar.gz
            ln -s roundcubemail-1.2.9 mail
            # menyiapkan database roundcube
            mysql -u root -p 
            CREATE DATABASE roundcubemail;
            GRANT ALL PRIVILEGES ON roundcubemail.* TO roundcube@localhost IDENTIFIED BY 'roundcube';
            FLUSH PRIVILEGES;
            cd /var/www/html/roundcube-1.2.9/SQL
            mysql -u root -p roundcubemail < ./mysql.initial.sql 

            # Mmengaktifkan plugins enigma
            cd /var/www/html/roundcube-1.2.9/config
            cp config.inc.php.sample config.inc.php

            # pgp roundcube
            chown www-data:www-data /var/www/html/mail/plugins/enigma/home

            service postfix restart -y        
            service apache2 restart
            ;;
        "Reset MAIL")
                echo "Mohon Bersabar ini Masih Install Mail server bos"
                apt-get purge postfix -y
                apt-get purge courier-imap courier-pop courier-ssl courier-imap-ssl
                #apt-get purge dovecot-imapd dovecot-pop3d -y
                apt-get purge squirrelmail -y
                rm /etc/apache2/sites-available/squirrelmail.conf
                a2dissite squirrelmail.conf                
                ;;
        "Quit")
            break
            ;;
        *) echo Pilihan anda salah;;
    esac
Menu    
done

